language: python
python:
    - "3.6"

install:
    - python setup.py install

script:
    - flake8 src
    - nose2
    - coord-sim -d 20 -n params/networks/Abilene.graphml -sf params/placements/Abilene.yaml
